kind: pipeline
name: build

steps:
- name: build
  image: golang:1.16-buster
  commands:
    - go build
    - go test

- name: docker
  image: plugins/docker
  environment:
        DOCKERHUB:
          from_secret: dockerhub
  settings:
    username: gigafyde
    password: $DOCKERHUB
    repo: gigafyde/apollo-lyrics
