kind: pipeline
name: build

steps:
  - name: build
    image: golang:1.16-buster
    commands:
      - go build
      - go test

  - name: docker
    image: plugins/docker
    settings:
      username: gigafyde
      password:
        from_secret: dockerhub
      repo: gigafyde/apollo-lyrics
